baseURL = "https://imtorgdemo.github.io/"
languageCode = "en-us"
title = "IMTorg Kbase"

theme = "hugo-theme-minos"
paginate = 10
[params]
    smartToc = true
    katex = true
    
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    
[[menu.main]]
    name = "Search"
    url = "/pages/search/"
    
[[menu.main]]
    name = "About"
    url = "/pages/about/"
